### ISSUE TITLE
ZIP files should either be compressed with "normal deflate" or not be compressed at all

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#144]
The underlying ZIP library (i.e. Java) does not handle compression very well I think. I got a compressed EPUB from Carl where not all files were extracted properly and I suspect the reason is that Java couldn't read the ZIP properly and for some reason failed silently when trying to unzip some of the files.

In my opinion we should not allow our EPUBs to be compressed. There shouldn't be too much to gain by compressing them anyway, the big files in our EPUBs are JPEG images and potentially MP3 audio for use in other production lines, and these are already compressed so that we won't gain much by compressing them again. Where compression is effective is on the content files themselves, but those won't be big enough that we really care about compression I think.

@TamJ what do you think?

**Comment by josteinaj** [comment]
**TODO:** investigate whether or not epubcheck already validates this.

**Comment by josteinaj** [comment]
There seems to be several ZIP related validations done in epubcheck, I'm not sure if the compression method is checked, but I would assume that epubcheck fails if it is unable to unzip the EPUB:

https://github.com/w3c/epubcheck/blob/master/src/main/resources/com/adobe/epubcheck/messages/MessageBundle.properties#L285

I suggest we close this issue, and leave this kind of validation up to epubcheck.

**Comment by martinpub** [comment]
Sounds like a good idea.
