### ISSUE TITLE
Consider using <img> for representation of foreign characters and other inline content

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#217]
This is apparently something we've done before. We should investigate whether this is something we still need to solve in EPUB and find a good way of marking this up.

**Comment by josteinaj** [comment]
Here's some examples of what will be allowed in the next version:


image in block context - with custom alt text:
```html
<img id="image-tests-img-11" src="images/image.jpg" alt="中国文字" />
```

image in inline context - with custom alt text:
```html
<p>
    <img id="image-tests-img-12" src="images/image.jpg" alt="中国文字" />
</p>
```

image in figure - with custom alt text:
```html
<figure id="image-tests-figure-8" class="image">
    <img id="image-tests-img-13" src="images/image.jpg" alt="中国文字" />
</figure>
```

image in image series figure - with custom alt text:
```html
<figure id="image-tests-figure-9" class="image-series">
    <figure class="image">
        <img id="image-tests-img-14" src="images/image.jpg" alt="中国文字" />
    </figure>
    <figure class="image">
        <img id="image-tests-img-15" src="images/image.jpg" alt="中国文字" />
    </figure>
</figure>
```

These examples demonstrate inline images and custom alt texts, both of which is useful for representing content that is better rendered as images than as characters, such as foreign characters or math.

**Comment by CarlRosschou** [comment]
Hi Jostein 
This is great. 
When do you expect the next version to be released?

**Comment by josteinaj** [comment]
I hope within a couple of weeks, but no guarantees.
