### ISSUE TITLE
Consider allowing other values than "image" on the img alt attribute to improve accessibility

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#218]
Image descriptions is an important part of making content accessible. While not all agencies have resources to do this as per today, it's something that is frequently mentioned and we should allow for adding image descriptions to the alt attributes in our guidelines.

**Comment by CarlRosschou** [comment]
Back to the img attibute. Nota would prefere any other value to be allowed, including empty ones. Validation should only depend on the presence of the attribute, the equal sign and the quotation marks.

**Comment by josteinaj** [comment]
http://www.w3.org/TR/WCAG20-TECHS/H67.html

An empty alt attribute makes screen readers ignore the image. We currently allow such images as long as they are not wrapped in a `<figure class="image">`.

I think the only thing we need to change is instead of checking for the string "image", we should check for any non-empty string.

From the link above it seems that we should probably check for the absence or emptyness of the title attribute as well.
