### ISSUE TITLE
Check JPEG headers for magic numbers and JFIF text; the same way as it's done in ZedVal

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#278]
@TamJ

**Comment by josteinaj** [comment]
Will make use of this: daisy/pipeline-modules-common#82 to solve this issue

**Comment by TamJ** [comment]
This fix may need to be tweaked. Our local ZedVal is still catching 'invalid' jpegs. I'll send over an epub example.

**Comment by josteinaj** [comment]
Yes, this fix is still not merged. Issues marked with "done" but are still "open" are fixed on my computer but not build as a JAR yet.

**Comment by TamJ** [comment]
Ok, Good! My bad. I didn't look closely at versions.

**Comment by josteinaj** [comment]
No problem :). Do you have a urgent need for this fix or were you just testing? I was planning to wait for some more fixes before releasing a new build, but I could make a new build now instead if you think that is better.

**Comment by TamJ** [comment]
Not urgent, really. We had several files today with this issue, but it's easily solved. In the meantime I can mention this issue to the folks authoring files, until the next build. THanks!
