### ISSUE TITLE
Ensure rowspan/colspan values don't excede table row/column dimensions

### ISSUE THREAD

**Issue by TamJ** [nlbdev/nordic-epub3-dtbook-migrator#295]
There seems to be a rule in the Pipeline 1 dtbook validation that checks for rowspan and colspan(?) values that excede element counts respectively:

"The rowspan attribute value is larger than the number of rows left in the table"

Maybe this could be added to the epub/dtbook validation?

**Comment by josteinaj** [comment]
Agreed.

**Comment by josteinaj** [comment]
This rule stems from this ZedVal feature request:
http://sourceforge.net/p/zedval/feature-requests/12/

The rules are still present in the official DP2 DTBook Validator which is invoked as part of the nordic DTBook validation so this rule should already be enforced for nordic DTBooks. I will try to add equivalent rules for EPUB/HTML. The DTBook validator also contains MathML validation rules which we can consider including if we choose to allow MathML in the future.

The DTBook rules are:

 * assert: There must be one and only one dtb:uid metadata item.
 * assert: Content of dtb:uid metadata may not be empty.
 * assert: There must be at least one dc:Title metadata item.
 * assert: Content of dc:Title metadata may not be empty.
 * assert: noteref URI value does not contain a fragment identifier.
 * report: noteref URI value does not resolve to a note element.
 * assert: annoref URI value does not contain a fragment identifier.
 * report: annoref URI value does not resolve to a annotation element.
 * assert: Internal link does not resolve.
 * report: The enum attribute is only allowed in numbered lists.
 * assert: The depth attribute on list element does not contain the list wrapping level.
 * assert: Not all the tokens in the headers attribute match the id attributes of 'th' elements in this or a parent table.
 * assert: Not all the tokens in the imgref attribute match the id attributes of 'img' elements.
 * assert: Not all the tokens in the imgref attribute match the id attributes of 'img' elements.
 * report: The accesskey attribute value is not 1 character long.
 * report: The tabindex attribute value is not expressed in numbers.
 * report: The accesskey attribute value is not unique within the document.
 * report: The tabindex attribute value is not unique within the document.
 * report: The char attribute value is not 1 character long.
 * report: char attribute may only occur when align attribute value is 'char'.
 * assert: The image width is not expressed in pixels or percentage.
 * assert: The image height is not expressed in pixels or percentage.
 * assert: Table width is not expressed in pixels or percentage.
 * assert: Table cellspacing is not expressed in pixels or percentage.
 * assert: Table cellpadding is not expressed in pixels or percentage.
 * report: The start attribute occurs in a non-numbered list.
 * report: The start attribute is not a non negative number.
 * report: Unrecognized Dublin Core metadata name.
 * report: Unrecognized Dublin Core metadata prefix.
 * report: span attribute is not a positive integer.
 * report: The rowspan attribute value is not a positive integer.
 * report: The colspan attribute value is not a positive integer.
 * report: The rowspan attribute value is larger than the number of rows left in the table.
 * assert: The value of the depth attribute on the level element does not correspond to actual nesting level.

(phew!)

**Comment by josteinaj** [comment]
Actually, since this rule should already be enforced during nordic DTBook validation it's a bit strange that you got this error from a nordic DTBook file...

**Comment by josteinaj** [comment]
should be fixed in be50447526751042fce0a0f7ca4226d46ea60837
