### ISSUE TITLE
Use hex-encoded entities for non-ASCII characters

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#297]
Either validate for it, or at least ensure that the non-ASCII characters in the DTBook are all hex-encoded (except for `&amp;`, `&gt;` and `&lt;`, those are probably fine as is). We can probably do this in XSLT using [`<xsl:output encoding="us-ascii"/>`](http://www.saxonica.com/documentation9.5/extensions/output-extras/character-representation.html).

**Comment by indy78** [comment]
Preferably hex-encoding should be validated in DTBook-conversion.

**Comment by josteinaj** [comment]
I will make sure that non-ASCII characters are hex-encoded when converting to DTBook.

We need to decide whether we want to validate for the presence of non-ASCII characters in the files we receive though.

**Comment by josteinaj** [comment]
fixed in deaf4ffcaeaa145a7b4e0d27828b33bc8c2069cd and 376ae2f8c33c39da69b506991bad25e02b8e246b
