### ISSUE TITLE
img not inside figure will not validate when converted to dtbook

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#313]
We've established a practice (#76, #132, #263) where images with a non-empty alt-attribute must be placed inside figure elements, and images with a empty alt-attribute must **not** be placed inside figure elements.

However, images not wrapped in figure elements will convert to images not wrapped in imggroup elements in DTBook, which is not allowed according to MTMs validation rule `tpb103`.

Possible solutions include:
 1. revert our practice and start requiring all images to be wrapped in figure elements
   * this is actually what's required in the guidelines
 2. remove the `tpb103` validation rule
   * we don't know what consequences this has to our DTBook-based production systems
 3. remove images with an empty alt-attribute from the DTBook output
   * they only serve a decorative purpose and I suspect we all discard them in our DTBook-to-braille systems anyway
 4. during conversion to DTBook, create a DTBook imggroup wrapper for images that has no figure wrapper in the HTML
   * the content models does not fit perfectly here as imggroup is not allowed in inline context so the conversion will have to try to do something clever like wrapping preceding and following sibling inline content in `<p>` elements and splitting wrapping block elements in two, etc. This can get complicated. We could alternatively require that all img elements be placed in a block context which would make wrapping them in imggroups much simpler.

Consider also issues #217, #218 and #219 while choosing a solution here.

I'm leaning towards the simplest solution which is to drop the images (alternative 3).

**Comment by CarlRosschou** [comment]
We have mainly used <img> elements outside of <figure> elements, for inline images of Chinese Characters, lists with symbols explained and the like. 
So We would appreciate if they somehow could be wrapped in <imggroup> elements in DTBook.

**Comment by josteinaj** [comment]
@CarlRosschou if the alt attribute is empty then the image should not be relevant for the understanding of the content. In your case, shouldn't you have content in the alt attribute? If you put content in the alt attribute you will also be required to wrap it in a figure though.

Wrapping img elements is not so straight forward because the DTBook content model for `<img>` and `<imggroup>` are different.

Would you be ok with solution 2; stop requiring imggroup wrappers in DTBook? Do you need all images to be wrapped in imggroups for your DTBook-based production systems?

@TamJ what do you think about removing MTMs rule here, do you require it?

**Comment by CarlRosschou** [comment]
Nota uses inline images in relation to textbooks for various educations on many occasions. Due to the nature of some tittles, it is impossible to avoid. We have had to leave the alt attributes empty in order to make the production pass validation. Therefore, we really favor including inline images in the guidelines.
We are increasingly adding alternate texts describing the content and function of the images. Thus, we want alternate texts not to be limited to only one or two words.

**Comment by indy78** [comment]
NLB would also benefit from allowing inline images (for use in HTML textbooks). NLB have no need for the <imggroup> wrapper.

**Comment by ManfredMuchenberger** [comment]
It shouldn't be a problem for us to make that change with the imggroup.
I am quite sure that we will need inline images at some point in future.
