### ISSUE TITLE
Check for nested levelx class=chapter

### ISSUE THREAD

**Issue by TamJ** [nlbdev/nordic-epub3-dtbook-migrator#314]
At MTM it seems we test whether level1-class=chapter contains a level2-class=chapter. I thought this existed in the validation test for the Pipeline 1 dist, but apparently not. 
Could this be a future validation tweek? The test in version 1.0 is:

``` xml
<xsl:template name="check-nested-chapters">
    <xsl:if test="count(//dtb:level1[@class='chapter' and dtb:level2[@class='chapter']])&gt;0"><xsl:message terminate="yes"><xsl:value-of select="$errorMsg-nestedChapters"/></xsl:message></xsl:if>
</xsl:template>
```

**Comment by josteinaj** [comment]
I thought this was validated for as well. If it's not there already I'm sure we can add it.

**Comment by josteinaj** [comment]
Let's avoid adding more rules for now. I'm closing this one. If this is something that is really important for MTM (or anyone else), we can reopen it and have a look at it again.
