### ISSUE TITLE
The EPUB3 validation rules currently seem to include line breaks when matching content values (experienced several times with [opf4]). Should we allow or disallow line brakes?

### ISSUE THREAD

**Issue by olavindergaard** [nlbdev/nordic-epub3-dtbook-migrator#323]

**Comment by josteinaj** [comment]
According to the [EPUB 3 specification](http://www.idpf.org/epub/30/spec/epub30-publications.html), whitespace should not be significant int metadata:

> Unless an individual property explicitly defines a different whitespace normalization algorithm, Reading Systems must trim all leading and trailing whitespace from the meta element values, as defined by the XML specification [XML], before further processing them.

In any case, the rule `[opf4]` (EPUB3 meta elements must have equivalent OPF2 meta elements) was removed in 16032178375ef3b5392325e9bd5ea1db51f20d49.
