### ISSUE TITLE
Allow epub:type="z3998:verse" markup in part

### ISSUE THREAD

**Issue by CarlRosschou** [nlbdev/nordic-epub3-dtbook-migrator#325]
A poem can appear in a part but the migrator does not allow it. 
([nordic211] 'z3998:verse' is not an allowed type in a part).

**Comment by josteinaj** [comment]
A poem is a non-structural component: http://www.daisy.org/z3998/2012/vocab/structure/#h_document-components

When converting from HTML to EPUB, all sections inside a part have been assumed to be structural components (chapters, etc.), and are split into separate HTML files.

I will try allowing non-structural components in parts.

**Comment by josteinaj** [comment]
Fixed in c2009a0a705999d411b8d3528f81d97bb2b1777c
