### ISSUE TITLE
Soften the requirement that all sectioning elements must be referenced from nav.xhtml

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#332]
Poems are marked up with the `<section>` element, so the validator currently requires that it is referenced from nav.xhtml and nav.ncx.

Consider ways of softening the requirement that all sectioning elements must be referenced from nav.xhtml.

I'm not sure if the markup guidelines actually say anything about this, but it probably should. I'm leaving this as a guidelines issue.

**Comment by rdeltour** [comment]
FYI, EDUPUB does require all sections to be in the Nav Doc. See also idpf/epubcheck#507

**Comment by josteinaj** [comment]
@rdeltour: Very interesting, thanks for the link!

So EDUPUB requires that all headings be referenced from the navdoc. It doesn't say that the entire document outline needs to be referenced though, so sectioning elements without headlines probably does not need to be referenced from the navdoc (which we currently require).

**Comment by josteinaj** [comment]
I don't think we should make any changes to this behavior in the migrator as that would probably be a significant modification. Closing.
