### ISSUE TITLE
Check for child elements in em

### ISSUE THREAD

**Issue by TamJ** [nlbdev/nordic-epub3-dtbook-migrator#351]
I've been battling with a large book where I discovered the following markup in html:

``` xml
<p class="line"><em><span class="linenum">130</span> And thirty dozen moons with borrowed sheen<a class="noteref" epub:type="noteref" href="#p1397007">7</a></em></p>
```
I haven't confirmed this yet but the child span may caause problems in the epub-to-dtbook conversion when the resulting linenum element becomes child to em.

**Comment by josteinaj** [comment]
Fixed in f8c4d37c6684485db63321cb7ca51d0b058c3f9b.

The markup in the issue description is no longer allowed. Linenums must be direct children of lines.
