### ISSUE TITLE
Make sure that epub:type values from the EPUB 3 Magazine Navigation Vocabulary are allowed

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#358]
https://idpf.github.io/epub-vocabs/structure/magazine/

**Comment by josteinaj** [comment]
@olavindergaard do you have links to any good references for marking up magazines in EPUB? The link above is not too informative and does not contain any examples.

**Comment by olavindergaard** [comment]
EPUB Region-Based Navigation Markup Informational Document has some examples: https://idpf.github.io/epub-guides/region-nav-markup/

**Comment by josteinaj** [comment]
## from magazine vocabulary:
- `prism:title`
- `prism:deck`
- `prism:subtitle`
- `prism:byline`
- `prism:contributors`
- `prism:caption`
- `prism:credit`
- `prism:box`
- `prism:advertisement`
- `prism:pullQuote`
- `msv:article-region`
- `msv:article-text`
- `msv:media`
- namespaces:
    - `msv: http://www.idpf.org/epub/vocab/structure/magazine/#`
    - `prism: http://www.prismstandard.org/specifications/3.0/PRISM_CV_Spec_3.0.htm#`
