### ISSUE TITLE
Conversion of dtbook epigraph can cause a p inside a p

### ISSUE THREAD

**Issue by egli** [nlbdev/nordic-epub3-dtbook-migrator#362]
When converting dtbook to epub3 `epigraph`s are converted to `p`. This can cause an non-valid epub as you can end up with a `p` inside a `p`. You say that you do not use `dtb:epigraph` in the [Mapping between HTML and DTBook](http://nlbdev.github.io/nordic-epub3-dtbook-migrator/mapping.html), so this is probably not an issue for you.

Would you accept a PR that just emits an `aside` instead?

BTW, @josteinaj I'm not sure if filing issues is the right way to go about this. If you would like a different channel please tell me :-)

**Comment by josteinaj** [comment]
Yes, feel free to submit a PR. That would be great.

Filing issues and PRs is good :)

**Comment by egli** [comment]
Superseded by #368
