### ISSUE TITLE
Conversion of dtbook prodnote can cause an aside inside a p 

### ISSUE THREAD

**Issue by egli** [nlbdev/nordic-epub3-dtbook-migrator#363]
Converting an inline `prodnote` to EPUB3 can cause an `aside` inside a `p` which isn't valid according to epubcheck. 

Would you accept a PR that fixes this?

The `aside` would have to be moved before or after the current `p`. Do you have any idea how this could be achieved?

See also sbsdev/pipeline#7

**Comment by josteinaj** [comment]
Yes, feel free to submit a PR. That would be great.

If you need to preserve the structure, then maybe you could just convert from `<prodnote>` to `<span epub:type="z3998:production" class="render-optional">`. That might not be valid according to the schemas though, but we could maybe allow that in the schemas as well.

If you want to move it before or after as an `aside`, then I suppose after would be preferable? No strong opinion though. Maybe it depends on the context. Why are the prodnotes inline in the first place?
