### ISSUE TITLE
Invalid HTML for dtbook:p inside dtbook:epigraph

### ISSUE THREAD

**Issue by egli** [nlbdev/nordic-epub3-dtbook-migrator#368]
The problem with epigraphs is not so much that we can have a `dtbook:epigraph` inside a `dtbook:p` (as described in #362 but that we can have `dtbook:p` inside `dtbook:epigraph`. This of course will also translate to `html:p` inside `html:p` which is not valid HTML5.

We propose to render `dtbook:epigraph` as `html:blockquote` as recommended by [WAI-ARIA](https://www.w3.org/TR/dpub-aria-1.0/#doc-epigraph). This will solve this issue and at the same time #362.

See also sbsdev/pipeline#11

**Comment by josteinaj** [comment]
Sounds good. Although, in the nordic migrator I think we should use `epub:type="epigraph"` instead of `role="doc-epigraph"`. Also, we should test to make sure that epigraphs are still converted back from HTML to DTBook properly.

**Comment by egli** [comment]
Hm, forgot about backtranslation. What's funny though is that [epub3-to-dtbook.xsl](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/master/src/main/resources/xml/xslt/epub3-to-dtbook.xsl#L462) is expecting an `html:aside`. On the other hand [dtbook-to-epub3.xsl](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/master/src/main/resources/xml/xslt/dtbook-to-epub3.xsl#L648) is producing `html:p`. So a round-trip doesn't seem to work anyway.

Not sure if we are interested in epub3-to-dtbook. But presumably for us it would have to convert to `dtbook:epigraph` while you want it to convert to `dtbook:p`. Correct?

**Comment by josteinaj** [comment]
Fixed in [v1.4.0](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/380).
