### ISSUE TITLE
Converting internal links without a fragment identifier results in an invalid link

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#372]
For instance, in the EPUB:

```html
<a href="563783-08-chapter-2.xhtml">kapittel 2</a>
```

After conversion to HTML this becomes:

```html
<a href="#">kapittel 2</a>
```

Which is invalid.

We should either forbid internal links without fragment identifiers, or look up the `@id` of the `<body>` element in the referenced file. Or both (so that we can handle old EPUBs).

**Comment by kalaspuffar** [comment]
Hi @josteinaj 

This rule might solve the issue of this bug but it will disallow telephone and mailto links.

```
    <pattern id="epub_nordic_273b">
        <rule context="html:a[not(matches(@href, '^[a-z]+:/+'))]">
            <assert test="matches(@href, '.*#.+')">[nordic273b] Internal links must contain a non-empty fragment identifier: <value-of
                select="concat('&lt;',name(),string-join(for $a in (@*) return concat(' ',$a/name(),'=&quot;',$a,'&quot;'),''),'&gt;')"/></assert>
        </rule>
    </pattern>
```

We triggered this rule when we tried to export a document with the following link:

<a id="d6e4162" title="" href="mailto:ebok@aschehoug.no" class="hyperlink">

Best regards
Daniel
