### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#373]
Extending the official docker image for the engine, adding the nordic migrator JAR file.

**Comment by egli** [comment]
I have a [Dockerfile](https://github.com/sbsdev/nordic-epub3-dtbook-migrator/blob/master/Dockerfile) which does just that. Do you want me to create a PR?

**Comment by josteinaj** [comment]
That would be great, thanks!

**Comment by josteinaj** [comment]
Fixed in [v1.4.0](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/380).
