### ISSUE TITLE
Find a way to write documentation inside the Schematron file, and generate HTML based on it

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#389]

**Comment by josteinaj** [comment]
There's actually some previous work here, although I'm not sure if we want to reuse it:

https://github.com/nlbdev/nordic-epub3-dtbook-migrator/commit/9e438fe063b45bbb97c3fb7309a0046ec32d020e
https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/gh-pages/schematron-to-html.sh
https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/gh-pages/schematron-to-html.xsl
https://nlbdev.github.io/nordic-epub3-dtbook-migrator/schemadoc/

**Comment by hugovanversendaal** [comment]
> There's actually some previous work here, although I'm not sure if we want to reuse it

I believe this previous work does the job pretty well.

During the last meeting you also suggested doing something like this (please correct me if I'm wrong):
```
<sch:pattern id="epub_nordic_7">
<h1>Nordic rule 7</h1>
<p>No &lt;ul&gt;, &lt;ol&gt; or &lt;dl&gt; inside &lt;p&gt;</p> 
        <sch:rule context="html:p">
            <sch:report test="html:ul | html:ol">[nordic07] Lists (<value-of select="concat('&lt;',name(),string-join(for $a in (@*) return concat(' ',$a/name(),'=&quot;',$a,'&quot;'),''),'&gt;')"/>) are
                not allowed inside paragraphs.</sch:report>
            <sch:report test="html:dl">[nordic07] Definition lists (<value-of select="concat('&lt;',name(),string-join(for $a in (@*) return concat(' ',$a/name(),'=&quot;',$a,'&quot;'),''),'&gt;')"/>) are
                not allowed inside paragraphs.</sch:report>
        </sch:rule>
    </sch:pattern>
```

This option requires adding another namespace to the schema if I'm not mistaken. I'm happy to explore this option, but I'm not sure it has advantages over your previous work.

By the way, we could use (or transform to) an HTML definition list for the output. How do you feel about that?

**Comment by josteinaj** [comment]
We don't need to add the HTML namespace if it's not necessary.

A definition list could work. I suppose the important thing is the readability; would it look nice as a definition list? How do you think it should be rendered? Something like this?:

---

<dl>
  <dt>[epub_nordic_7] Nordic rule 7: No &lt;ul&gt;, &lt;ol&gt; or &lt;dl&gt; inside &lt;p&gt;</dt>
  <dd>Lists (…) are not allowed inside paragraphs.</dd>
  <dd>Definition lists (…) are not allowed inside paragraphs.</dd>
</dl>

---

Or maybe this?:

---

<h3>Nordic rule 7</h3>
<p>No &lt;ul&gt;, &lt;ol&gt; or &lt;dl&gt; inside &lt;p&gt;</p>
<dl>
  <dt>epub_nordic_7a</dt>
  <dd>Lists (…) are not allowed inside paragraphs.</dd>
  <dt>epub_nordic_7b</dt>
  <dd>Definition lists (…) are not allowed inside paragraphs.</dd>
</dl>

---

We might not even need documentation for each sch:report as long as the documentation for the sch:pattern/sch:rule is good enough:

---

<dl>
  <dt>epub_nordic_7</dt>
  <dd>No &lt;ul&gt;, &lt;ol&gt; or &lt;dl&gt; inside &lt;p&gt;</dd>
</dl>

---

**Comment by hugovanversendaal** [comment]
> We might not even need documentation for each sch:report as long as the documentation for the sch:pattern/sch:rule is good enough

This would definitely result in a lighter documentation. The documentation could then be written in comment nodes (as is done for a lot of rules now) and transformed to html. On the other hand maybe some people would want the complete documentation for all the assert/report tests? Shall we discuss this tomorrow at the meeting?

By the way I've generated a basic `dl` using an altered version of your xsl, and I don't think it looks as nice as your `table` version.
[nordic2015-1-test.zip](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/files/5483230/nordic2015-1-test.zip)

So we have a couple of options to discuss:
- should we use the text nodes of the sch:assert and sch:report to generate html documentation (complete), or the comment nodes (simpeler), or a combination?
- What should the html output look like? A table? A list? Sections?

**Comment by hugovanversendaal** [comment]
I've copied the the original nordic2015-1.sch file and applied the title/p method instead of comment nodes as discussed in the last meeting. See also Martin's suggestion in [#391 ](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/391)
[nordic2015-1-test.zip](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/files/5519050/nordic2015-1-test.zip)

What is a good way to proceed? Can I place the above schematron file in the validator repo, name it 2020-1 and so we can edit it further?

**Comment by josteinaj** [comment]
Looks great!

Yes, if you check out the `guidelines-revision` branch, you'll find a folder named `src/main/resources/xml/schema/2020-1` where you can edit and commit/push as you please.

**Comment by hugovanversendaal** [comment]
Thanks, the changes are committed!

Moving on to creating HTML output now.

**Comment by hugovanversendaal** [comment]
I've been having some fun with XSL and CSS. See the attached zip file with the stylesheet and the HTML output. It contains two markup alternatives: table and sections. I prefer the table, because it's easy to spot the rules that don't have a description yet.

[nordic2020-schematron-to-html.zip](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/files/5533610/nordic2020-schematron-to-html.zip)

**Comment by josteinaj** [comment]
Looks great! I like the table alternative as well.

**Comment by martinpub** [comment]
Great work @hugovanversendaal. I like the table version too.

**Comment by hugovanversendaal** [comment]
Thanks for the feedback. I could remove the second markup to keep it clean.

What would be a good place to store these files, so we can acces them easily? After that, I suppose we can close this issue.

**Comment by josteinaj** [comment]
I guess you could put the files into the `documentation` directory at the top of the project directory.

**Comment by hugovanversendaal** [comment]
I removed the section alternative and uploaded the stylesheet and the current HTML output:
[nordic2020-schematron-to-html.xsl](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/documentation/nordic2020-schematron-to-html.xsl)
[nordic2020-1.html](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/documentation/nordic2020-1.html)

**Comment by josteinaj** [comment]
Great job, thanks!

Let's consider this done. We can update the XSLT later if there's anything we want to change.
