### ISSUE TITLE
Find a way to write documentation inside the RelaxNG file, and generate HTML based on it

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#390]

**Comment by josteinaj** [comment]
As mentioned in our meeting today, we will initially focus on making the RelaxNG look good in the interactive Oxygen XML Editor view. This means adding `<a:documentation>` elements and changing `<definition>`/`<ref>` names where appropriate, to make it easier to understand the RelaxNG when using Oxygen.

Although this focuses on Oxygen, it will also make the documentation better for other editors, for rendering as SVG (as @tagerobert experimented a bit with), as well as simply when reading the XML directly.

**Comment by tagerobert** [comment]
I have added comments into doc-elements. Use oxygen-developer to display a split screen view of the RelexNG:
![image](https://user-images.githubusercontent.com/30653687/100587058-613f2480-32f0-11eb-8e81-8b09889c07cf.png)

The changed file nordic-html5.rng can be viewed and downloaded from github: 

https://github.com/nlbdev/nordic-epub3-dtbook-migrator/tree/guidelines-revision/src/main/resources/xml/schema/2020-1
