### ISSUE TITLE
Write human readable documentation for all the Schematron validation rules

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#391]
Initially, until there's a better solution (see #389), you can just put the text in XML comments:

```xml
<!-- Human readable description of the validation rule here -->
<pattern id="…">
```

**Comment by martinpub** [comment]
I will be happy to work with this, with the disclaimer that I might not be able to decode all rules. Unfortunately, I haven't been able to work on this yet, so my time is limited currently, sorry.

Also, I see that schematron has the elements `title` and `p`, which could be used for description? See also #389.

**Comment by hugovanversendaal** [comment]
The Schematron file on the guidelines-revision branch now has `title` and `p` elements for adding documentation: [nordic2020-1.sch](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/schema/2020-1/nordic2020-1.sch).

**Comment by josteinaj** [comment]
Looks great!

Do you think you could do the same for `nordic2020-1.nav-ncx.sch` (8 rules), `nordic2020-1.nav-references.sch` (4 rules), `nordic2020-1.opf-and-html.sch` (15 rules) and `nordic2020-1.opf.sch` (18 rules)?

**Comment by hugovanversendaal** [comment]
Sure, no problem. I'll get to that this afternoon.

**Comment by josteinaj** [comment]
Maybe add a visible timestamp to the generated HTML.
