### ISSUE TITLE
Gather information from all agencies about how they want to use the validator/migrator

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#394]
- Manually and/or automatic?
- Using one of the Pipeline 2 clients (Web UI, desktop application, command line)?
- Running on a server or on personal computers?
- Use it in an XML editor like oXygen?

See also (actually a duplicate, but oh well, let's just keep both): https://github.com/nlbdev/epub3-guidelines-update/issues/24

**Comment by josteinaj** [comment]
I'll ask the steering group about this, but feel free to start gathering information from your own agencies.

**Comment by martinpub** [comment]
Here are MTM's thoughts. We will be happy to elaborate if anything is unclear.

>     Manually and/or automatic?

Primarily automatic, as we want to invoke the validator by calling it from our production management system, which talks to the Pipeline 2 API.

>     Using one of the Pipeline 2 clients (Web UI, desktop application, command line)?

We will probably be using the REST API for talking to Pipeline 2, but having the validator work in the other interfaces is probably also good. Also considering the Indian suppliers as one of the main user groups here.

>     Running on a server or on personal computers?

Primarily on a server, but we are also interested in local validation on operators' personal computers. The server solution is priority 1 however.

>     Use it in an XML editor like oXygen?

If the validator rules can be applied in a non-Pipeline 2-dependent form, for processing in external XML editors as oXygen, I guess this would be a nice feature too, but again, not highest priority.

**Comment by martinpub** [comment]
I want to clarify one thing: I think a more manual approach to using the validator is used by our EPUB 3 producers. So the typical use-case there would be that they validate the file in Pipeline 2 (currently using the Nordic migrator) before sending it to us for delivery. The possibility to port the validation rules to an XML editor context could be useful also for the EPUB 3 producers.

**Comment by josteinaj** [comment]
Based on feedback from Celia:

- Ordering both EPUB and DTBook
- Editing and using the DTBooks as the source file for the distribution copies (audio etc.)
- Using Pipeline 1 inhouse for validating DAISY 2.02 and DTBook

**Comment by josteinaj** [comment]
Based on feedback from SPSM:

- Would like a validator separate from Pipeline 2, because they've had trouble (both internally and externally) with installing and running it properly.
- Running the validator from the command line would be useful
- It's not important whether or not it is run on a server or locally
- Running the validation in Oxygen would be useful, but it's not important

**Comment by hugovanversendaal** [comment]
> Manually and/or automatic?
Manually: our short-term plan is to keep producing and editing in DTBook, and then to convert and validate each EPUB manually before archiving and distribution. We use the Nordic migrator scripts for this. In mid to long-term we will probably want to switch to automatic.
> Using one of the Pipeline 2 clients (Web UI, desktop application, command line)?
Probably CLI, maybe Web UI. We're currently experiencing memory issues with the Pipeline's Web UI, so we try to avoid it for now.
> Running on a server or on personal computers?
Running on a server.
> Use it in an XML editor like oXygen?
As long as Dedicon keeps using DTBook as a production format, we probably wouldn't use it like that. But if we would switch to editing EPUB, this would definitely be a convenient feature.

**Comment by josteinaj** [comment]
Moved from https://github.com/nlbdev/epub3-guidelines-update/issues/24: 

> 'Use it in an XML editor such as oXygen' seems desirable. - @TorilBWM

**Comment by josteinaj** [comment]
We haven't got a response from HBS or Nota (unless I've missed something). But here's a summary of the responses so far:

#### Manually and/or automatic?

Both.

#### Using one of the Pipeline 2 clients (Web UI, desktop application, command line)?

Web UI, REST API, Command Line.

#### Running on a server or on personal computers?

Server.

#### Use it in an XML editor like oXygen?

Not important, but could be useful.

#### Other notes

DTBook is still being used by several agencies. In general it seems that those who make manual edits, do so in the DTBook version.
