### ISSUE TITLE
Make it possible to validate without Pipeline 2

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#395]
Try to modify the validation rules so that validation can be run outside of Pipeline 2, such as in an XML editor. It would be convenient to be able to validate (maybe just partially validate) the EPUBs according to our validation rules when you're working in an XML editor. If Oxygen XML Editor is used by almost everyone, then maybe we could make a semi-official oxygen scenario that can be easily installed. We'll have to gather more information first (#394) before we know whether or not this is something we want to do.

#### Pipeline 2 not needed, can already be used outside of Pipeline 2:

- [x] [nordic2020-1.opf.sch](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/schema/2020-1/nordic2020-1.opf.sch) (the OPF file)
- [x] [nordic-html5.rng](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/schema/2020-1/nordic-html5.rng) (each HTML file separately)
- [x] [nordic2020-1.sch](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/schema/2020-1/nordic2020-1.sch) (each HTML file separately)

#### Pipeline 2 used to preprocess documents before validation:

- [ ] [nordic2020-1.opf-and-html.sch](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/schema/2020-1/nordic2020-1.opf-and-html.sch) (the OPF and all the HTML files)
- [ ] [nordic2020-1.nav-references.sch](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/schema/2020-1/nordic2020-1.nav-references.sch) (the navigation document and all the HTML files)
- [ ] [nordic2020-1.nav-ncx.sch](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/schema/2020-1/nordic2020-1.nav-ncx.sch) (the navigation document and the NCX, if present)

#### Validations performed in Pipeline 2 that are not based on Schematron or RelaxNG:

- [ ] [px:read-xml-declaration](https://github.com/daisy/pipeline/blob/master/modules/common/file-utils/src/main/resources/xml/xproc/read-xml-declaration.xpl) (used to validate that the XML declaration is correct)
- [ ] [px:read-doctype](https://github.com/daisy/pipeline/blob/master/modules/common/file-utils/src/main/resources/xml/xproc/read-doctype.xpl) (used to validate that the DOCTYPE is correct)
- [ ] [px:nordic-check-image-file-signatures](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/xproc/step/check-image-file-signatures.xpl) and [px:file-peek](https://github.com/daisy/pipeline/blob/master/modules/common/file-utils/src/main/resources/xml/xproc/peek.xpl) (used to validate the image file signatures)

**Comment by josteinaj** [comment]
#### Pipeline 2 not needed, can already be used outside of Pipeline 2:

- [ ] [nordic2020-1.opf.sch](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/schema/2020-1/nordic2020-1.opf.sch) (the OPF file)
- [ ] [nordic-html5.rng](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/schema/2020-1/nordic-html5.rng) (each HTML file separately)
- [ ] [nordic2020-1.sch](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/schema/2020-1/nordic2020-1.sch) (each HTML file separately)


#### Pipeline 2 used to preprocess documents before validation:

- [ ] [nordic2020-1.opf-and-html.sch](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/schema/2020-1/nordic2020-1.opf-and-html.sch) (the OPF and all the HTML files)
- [ ] [nordic2020-1.nav-references.sch](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/schema/2020-1/nordic2020-1.nav-references.sch) (the navigation document and all the HTML files)
- [ ] [nordic2020-1.nav-ncx.sch](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/schema/2020-1/nordic2020-1.nav-ncx.sch) (the navigation document and the NCX, if present)


#### Validations performed in Pipeline 2 that are not based on Schematron or RelaxNG:

- [ ] [px:read-xml-declaration](https://github.com/daisy/pipeline/blob/master/modules/common/file-utils/src/main/resources/xml/xproc/read-xml-declaration.xpl) (used to validate that the XML declaration is correct)
- [ ] [px:read-doctype](https://github.com/daisy/pipeline/blob/master/modules/common/file-utils/src/main/resources/xml/xproc/read-doctype.xpl) (used to validate that the DOCTYPE is correct)
- [ ] [px:nordic-check-image-file-signatures](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/xproc/step/check-image-file-signatures.xpl) and [px:file-peek](https://github.com/daisy/pipeline/blob/master/modules/common/file-utils/src/main/resources/xml/xproc/peek.xpl) (used to validate the image file signatures)

**Comment by josteinaj** [comment]
@kalaspuffar where are we on this one?

@oscarlcarlsson have you worked on this? done any testing?

**Comment by oscarlcarlsson** [comment]
@josteinaj as far as i know, the latest version can be run outisde of pipeline2. We are still not using Oxygen in general at MTM.

**Comment by josteinaj** [comment]
This issue description is a bit fuzzy. If it's only about *running* without Pipeline 2, then this is solved. But I think Pipeline 2 is still part of the build process, and the validation rules cannot be run outside of this project in a pure oxygen environment (or other editors). So we just need to decide whether or not we consider this issue done or not.

**Comment by josteinaj** [comment]
I'm closing this for now. If we want to pursue this in the future, then we should describe a more concrete use case and success criteria.
