### ISSUE TITLE
Update validation rules based on feedback: the structure of the content files

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#409]
RelaxNG: https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/guidelines-revision/src/main/resources/xml/schema/2020-1/nordic-html5.rng

- Update nordic-html5.rng based on feedback from the guidelines group: https://github.com/nlbdev/epub3-guidelines-update/issues/95

**Comment by josteinaj** [comment]
Allow two types of nesting for lic: li/lic/a and li/a/lic. See: https://github.com/nlbdev/epub3-guidelines-update/issues/105#issuecomment-758662200

**Comment by martinpub** [comment]
Not sure if the lic nesting types was implemented? Ping @AndersEkl @kalaspuffar

**Comment by kalaspuffar** [comment]
Hi @martinpub 

After testing I realized that this is implemented as expected.

My test case that is allowed:

```
            <ul>
                <li>
                    <span class="lic">Normal LIC</span>
                </li>
                <li>
                    <span class="lic">
                        <a href="http://example.com">http://example.com</a>
                    </span>
                </li>
                <li>
                    <a href="http://example.com">
                        <span class="lic">http://example.com</span>
                        <span class="lic">http://example.com</span>
                    </a>
                </li>
            </ul>
```

Best regards
Daniel

**Comment by martinpub** [comment]
Great, closing then.
