### ISSUE TITLE
Validator issue: [nordic_nav_references_2a], incomplete documentation and possibly broken rule

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-epub3-dtbook-migrator#439]
In the validation of the test book XA60352A, errors like the following occur even for what seems to be valid section references:

> `[nordic_nav_references_2a] All references from the navigation document must reference either a sectioning element in one of the content documents: (<a href="X60352A-13-chapter.xhtml#level3_11">)`

The documentation seems to be an incomplete sentence, so perhaps something else is wrong with how this rule is currently expressed?

Ping @AndersEkl @kalaspuffar

**Comment by AndersEkl** [comment]
Wasn't it the pagination validation that seemed to be duplicated?

**Comment by martinpub** [comment]
Yes, sorry, just noticed it myself, removing that sentence.

**Comment by martinpub** [comment]
Perhaps it's just a typo, so "either a" should be changed to "exactly one"?

**Comment by kalaspuffar** [comment]
Handled in PR #451
