### ISSUE TITLE
Validator issue: [nordic_opf_and_html_23] Insufficient documentation for easily locating error, and possible duplicate

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-epub3-dtbook-migrator#440]
For the following output:

> `[nordic_opf_and_html_23] pagebreak values must increase for pagebreaks with class="page-normal" (see pagebreak with aria-label="" in webarch-obf-and-html.xml and compare with pagebreak with aria-label=" in webarch-obf-and-html.xml)`

XPath is included as tooltip info in the HTML output, but it is hard to resolve since it doesn't include the filename.

Including ID of the incorrect page breaks would be a good idea, since they are globally unique.

Also, this seems to be included in the per-content document check, so perhaps this is a duplicate check?

Ping @kalaspuffar @AndersEkl

**Comment by kalaspuffar** [comment]
Hi @martinpub 

This check looks at the numbering of the aria-label. This was incorrect earlier as there was no aria-label to be found. Now that this is updated the rule is valid.

> aria-label=""

Best regards
Daniel
