### ISSUE TITLE
Validator issue: [xhtml] Line: 13 Col: 1705 text not allowed here; expected the element end-tag  (X60352A-13-chapter.xhtml)

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-epub3-dtbook-migrator#442]
Markup triggering this error:

`<li id="li_9" value="9">Rist'kateisei-s'je t&#xf6; muga: Tat meiden, kudam taivhil! i sv&#xe4;tikahase nimi sinun.<span id="Page_24" class="page-normal" epub:type="pagebreak" role="doc-pagebreak" title="24">24</span></li>`

Is this an EPUBCheck error? It seems to be a correct use of span inside an li?

Ping @kalaspuffar @AndersEkl

**Comment by kalaspuffar** [comment]
Hi @martinpub 

There is a couple of different rules in the validation report.
```
[epubcheck]
[ace]
[xhtml] = RelaxNG
[nordic_*] = Schematron
```

Sadly the RelaxNG rules are the most in need of review, and there is a lot to change. In this case, I forgot to add Text as an allowed child of a page break span. We allowed it for block page breaks.

Best regards.
Daniel

**Comment by martinpub** [comment]
I see. Thanks for explaining the different rule names!
