### ISSUE TITLE
IDs not allowed on `<div class="verse">`

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-epub3-dtbook-migrator#452]
In `<div class="verse" id="poem_1">`, the validator (RelaxNG) does not allow additional attributes so the id makes it invalid. This should be opened up, as IDs should be generously allowed.

**Comment by martinpub** [comment]
Hi @kalaspuffar, don't know if you saw this, pinging to make sure.

**Comment by kalaspuffar** [comment]
Hi @martinpub 

Added basic types to the poem element.
https://github.com/nlbdev/nordic-epub3-dtbook-migrator/pull/454

Best regards
Daniel
