### ISSUE TITLE
Allow `<p class="verse-author">`

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-epub3-dtbook-migrator#453]
`<p class="verse-author">(Scherz, List und Rache 25.)</p>`  is currently not allowed in RelaxNG. Both the class value and the fact that it should be able to occur without line spans should be added.

See https://format.mtm.se/nordic_epub/2020-1/#poetry-and-verse.

**Comment by martinpub** [comment]
Hi @kalaspuffar, don't know if you saw this, pinging to make sure.

**Comment by kalaspuffar** [comment]
Hi @martinpub 

This is allowed in poems. And line-by-line groups.

Best regards
Daniel

**Comment by kalaspuffar** [comment]
In https://github.com/nlbdev/nordic-epub3-dtbook-migrator/pull/454 we now allow the element to contain text as well :)

**Comment by martinpub** [comment]
Great, thanks!
