### ISSUE TITLE
Allow `<hr class="separator">` in between different block elements?

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-epub3-dtbook-migrator#455]
Currently, the RelaxNG rules only allow `<hr class="separator">` in between `<p>`s. The [guidelines](https://format.mtm.se/nordic_epub/2020-1/#thematic-breaks-in-the-text-flow) do not provide that level of contextual detail, but there might be cases were a separator should be allowed even if the separated block elements are different, e.g. `<p>` and `<blockquote>`.

Can we open up for a less restrictive separator validation rule?

(Ping @AndersEkl, @kalaspuffar)

**Comment by martinpub** [comment]
p + hr + blockquote was what triggered in the test book. Not sure what is the best way forward here, would it be to allow it as a regular block element anywhere similar to other blocks? What do you say @AndersEkl? I think that we need to bring up a clarification of the appropriate use of hr in the guidelines group, so this is how strict validation should be while waiting for that :-)

**Comment by kalaspuffar** [comment]
Hi @AndersEkl 

Well I've not tried this but I could think that situation like

```
<table>
        <tr>
            <th><hr/></th>
        </tr>
        <tr>
           <td>Some content <hr/> some other content</td>
        </tr>
</table>
```

Could be hard to layout in braille and perhaps even crash some readers. But if you have checked that all readers support HR in all contexts the change to allow it everywhere should be a minor change.

Best regards
Daniel

**Comment by AndersEkl** [comment]
@kalaspuffar There are several other elements that could be used in contexts that are not desirable, but would be allowed by the validator. So I don't know if we should single out just `<hr>` to be very strict about.

**Comment by kalaspuffar** [comment]
@AndersEkl True true, we could reach the appropriate validation in at least two ways. Either allow it everywhere and make it more strict as users find issues with reading it. Or allow it in more places where producers have problems creating correct documents.

**Comment by AndersEkl** [comment]
Ideally, we would want to allow it anywhere in a continuous text context, I think, but not inside other types of constructs, such as tables. But maybe we are overthinking things? Would we start seeing `<hr>` being used all over our books if we loosen up the strictness? @martinpub what do you think?

**Comment by AndersEkl** [comment]
@kalaspuffar Still, the link you sent categorizes `<hr>` as flow content. Thus, it is acceptable to use wherever flow content is expected.

**Comment by martinpub** [comment]
Thanks @AndersEkl, that's a good point.

I can think of even a fiction context where p + hr + blockquote would be appropriate: Say you have a novel using regular indentation to mark p:s, then using a separator to indicate thematic breaks, e.g. super paragraphs. Currently we don't require those to be captured with nesting `<section>`s, but are OK with `<hr>` instead. It could be then that the novel's narration sometimes cites a letter, a diary, or something, that is marked up with `<blockquote>`. And this content may very well be located after a separator. So it should be allowed.

**Comment by martinpub** [comment]
We discussed this in today's call. The conclusion was to make an adjustment to allow `<hr>` with `<p>` on any side, which is a compromise but will make the issue in X50525A valid. The guidelines group can continue the discussion in a revision.
