### ISSUE TITLE
Bridgehead is not allowed in `<aside>`

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-epub3-dtbook-migrator#460]
Current rule: [nordic270] Bridgehead is only allowed as a child of section, article and div. (`<p epub:type="bridgehead">`).

According to the guidelines text, they does not seem to be forbidden in asides:

> Headings in text boxes is by default required to be marked up using <p epub:type="bridgehead">. These are structurally unimportant headings and will not be included in the navigation document. If, however, certain text boxes should be included in the navigation document, they must be marked up using a <h[x]> element of an appropriate level, following the level structure of the surrounding text. Only text boxes marked up with <aside> can have <h[x]> headings. The Ordering Agency will specify in the Editing Instructions if <h[x]> markup is required.

Even though I know ACE complains when we have untitled (as in no aria-labelledby/aria-label) asides, but according to how the guidelines text is currently formulated, I think bridgehead should be allowed in asides, right @AndersEkl?

Ping @kalaspuffar

**Comment by AndersEkl** [comment]
Yeah, that sounds reasonable to me.

**Comment by kalaspuffar** [comment]
Hi @martinpub 

Bridgehead is allowed using ```epub:type```, but the example above is not a ```sidebar```. It's a ```text-box```. Sidebars need to have the class="sidebar" to distinguish from other aside elements.

I looked into https://format.mtm.se/nordic_epub/2020-1#sidebars-text-boxes-etc.

Does this mean that class ```sidebar``` or ```text-box``` should be interpreted as sidebars or is any other classes that will be used here?

Best regards
Daniel

Best regards
Daniel

**Comment by martinpub** [comment]
Hi @kalaspuffar. For all purposes, the class "sidebar" was deprecated and replaced by class "text-box" with the 2020-1 guidelines. I hope this clarifies the issue.

Ping @AndersEkl

**Comment by AndersEkl** [comment]
The class attribute "sidebar" was present to map elements to the DTBook element `<sidebar>`. The way `<sidebar>` was used previously was not semantically correct. It was used for all sorts of purposes, regardless of if the content was part of the main text or not. Semantically, `<sidebar>` should be only content that is not part of the main text. This function is very similar to the `<aside>` element in HTML. The class attribute "text-box" is only meant as an styling indicator and can be used for both secondary content, marked up with `<aside>`, and content that is integral to the main text, marked up with `<div>`. I don't see any need for the class attribute "sidebar" any more, as the semantic function is carried by which HTML element is used.

Bridgeheads need to be allowed for "text-box" content regardless of what element it is contained in.

I hope that clarifies things.

**Comment by kalaspuffar** [comment]
Hi @AndersEkl 

Not really, but I guess the fix I've created is not what you want. When the change has been clarified I could implement it. If we are in a situation where everything should be allowed again we might need to discuss it in the group at the next meeting.

Best regards
Daniel

**Comment by AndersEkl** [comment]
"Sidebar" is no longer used as a class attribute. Bridgehead should be allowed in `<aside>` elements in addition to the previously allowed contexts. I don't think it is more complicated than that, really.

**Comment by martinpub** [comment]
I agree with @AndersEkl. See also my comment in #469. Let me know if you have any remaining questions @kalaspuffar, and we will be happy to discuss further.
