### ISSUE TITLE
Add check for backlink presence in footnotes/endnotes

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-epub3-dtbook-migrator#478]
Currently, we don't have a rule that checks backlink presence for footnotes/endnotes, so this should be added.

The [current text of the Nordic Guidelines](https://format.mtm.se/nordic_epub/2020-1#notes-and-note-references) is not exact on which of the two methods for backlinks from the DAISY KB should be preferred in 2020-1, so to begin with, we should check both or any method (always including `@role="doc-backlink"`). Is link integrity check enough, or should we implement a cross-reference check that ensures that the backlink target is equal to the referencing noteref of the present footnote?

**Comment by martinpub** [comment]
Implement a rule including presence of backlink check, and also check target to be the correct footnote ref.

**Comment by josteinaj** [comment]
Was this solved by #509?

**Comment by martinpub** [comment]
Yes @josteinaj, this is solved by #509, I will close this now. Thanks!
