### ISSUE TITLE
Merge guidelines-revision to master and make an official release

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#500]
@martinpub @kalaspuffar let me know when you think the `guidelines-revision` branch is in a state when we can make an official release.

The release would also be useful for 2015-1 validation and migration as it would contain a newer Pipeline 2 underneath the hood.

**Comment by josteinaj** [comment]
…also, document how it's done: #501

**Comment by martinpub** [comment]
Thanks @josteinaj, this will be much appreciated, and it will be a nice addition to the somewhat informal release process we have worked with (guidelines-revision branch with date tags for continuous releases) during your absence :-).

I suggest we discuss this at the next validation meeting, next week.

**Comment by josteinaj** [comment]
I'm sorry I wasn't able to do this sooner. The release process should now be somewhat simpler so hopefully I won't be required for every release going forward.

I've made a release now. Version 1.5.0:

- Maven repository (now on Github): https://github.com/nlbdev/nordic-epub3-dtbook-migrator/tree/mvn-repo/org/daisy/pipeline/modules/nordic-epub3-dtbook-migrator/1.5.0
- Github release: https://github.com/nlbdev/nordic-epub3-dtbook-migrator/releases/tag/v1.5.0

The Docker image has not finished building yet, but unless something goes wrong, it will be available very soon: https://hub.docker.com/r/nlbdev/nordic-epub3-dtbook-migrator

**Comment by josteinaj** [comment]
The docker image is built, and I have done some quick tests. When epubcheck is enabled, which it is by default, then there's an error:

- https://github.com/nlbdev/nordic-epub3-dtbook-migrator/issues/512

**Comment by josteinaj** [comment]
The branch is now merged, so I'm closing this issue. The epubcheck report parsing bug can be followed up in #512.
