### ISSUE TITLE
Document release process

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#501]

**Comment by josteinaj** [comment]
I have changed from sonatype + maven central to using a branch on Github as a maven repository. It makes it easy for anyone with access to this repository to make a release. The documentation in the README should also be up to date now (but of course, there's always room for improvement). The guidelines-revision branch is still not merged to master, but that's just a matter of time (very soon).

**Comment by egli** [comment]
> I have changed from sonatype + maven central to using a branch on Github as a maven repository

That seems a bit unconventional. I helped to automated the release process for [liblouis-nar](https://github.com/liblouis/liblouis-nar) using github actions. At first we used the github package archive which was very easy to set up, see [Publishing packages to GitHub Packages](https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven#publishing-packages-to-github-packages). But Bert wanted to use a more standard repo so we ended up with a slightly more complicated workflow, see the [workflow file](https://github.com/liblouis/liblouis-nar/blob/master/.github/workflows/main.yml#L86).

**Comment by josteinaj** [comment]
I tried Github Packages for [spell-no](https://github.com/nlbdev/spell-no/). It worked great, but it requires authentication to download artifacts which is annoying. I've read that GitLab has something similar that works without authentication, which could be an alternative.

Using a separate branch is a bit unconventional, yes, so it wasn't my first choice. But it's not something I've invented either. I've based it on what others are doing.

My reason for using a branch is that it is much simpler for new developers to make a release.

The nordic migrator doesn't really need to be in a maven repository at all. It just needs the JAR file to be hosted somewhere and available for download. So one could argue that using Github releases would be better, if we don't need a maven repo. It's not used as a maven artifact in any build process as far as I'm aware of.

But if we can fully automate the release process to maven central through sonatype that would be great. Do you think it would be straight forward to do that for this project?
