### ISSUE TITLE
Problem validating 2015-1 EPUBs

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#515]
I'm getting this when trying to validate 2015-1-EPUBs:

```
SetDoctype: px:set-doctype failed to read from /opt/daisy-pipeline2/data/jobs/…/output/html-report/report.xhtml
```

The job succeeds, but there's no report.xhtml to present in the web interface. It just gives that error in the log.

@martinpub @AndersEkl can you reproduce this behavior?

**Comment by martinpub** [comment]
No, I just validated a 2015-1 EPUB just fine in v1.5.2 (Docker). The report.xhtml file is correctly produced.

Possibly related to Pipeline version? I know there was [this issue](https://github.com/daisy/pipeline-modules/commit/78708687b4051a07bb832d6de8f73750d81da262) for instance. No idea if related.

**Comment by josteinaj** [comment]
Ok, hmm. did you use the Web UI? If not, maybe there's an issue wrt the Web UI.

**Comment by martinpub** [comment]
Yes, this was with web UI v.2.7.1.

**Comment by oscarlcarlsson** [comment]
I have tried to run some tests on 2015-1 epubs in the latest version of the validator. It seems to trigger errors related to 2015-1 guidelines now.

**Comment by oscarlcarlsson** [comment]
I have run some more tests and the issues seem to be based markup in certain files. It might be a good idea to have someone who is currently using the 2015-1 guidelines to run some files to make sure that there are no false positives that pass through, though. But, from my end this can be closed now.

**Comment by josteinaj** [comment]
Is it the same errors in the latest official version (v1.5.2, based on Pipeline 2)? Are the same EPUBs valid in both the current and the new validator?

**Comment by oscarlcarlsson** [comment]
The errors does not seem to be validator related. So this is not an issue any more.
