### ISSUE TITLE
doc-noteref not required on noteref elements, but should

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-epub3-dtbook-migrator#520]
The validation rules for 2020-1 currently allow omitting `@role="doc-noteref"` on noteref `<a>` elements. Hopefully this will be caught by ACE, but as it is specified in the 2020-1 guidelines explicitly, I think it should be added to the list of required attributes of a noteref element. I think it's [around here in the Schematron schema](https://github.com/nlbdev/nordic-epub3-dtbook-migrator/blob/b77d614dca69309bfa574870d0d02fd511df7449/src/main/resources/xml/schema/2020-1/nordic-html5.rng#L2801-L2814).

Possibly, specific checks of other role values in other contexts should also be added, but I haven't looked into that.

**Comment by josteinaj** [comment]
@martinpub @kalaspuffar solved?

**Comment by kalaspuffar** [comment]
To my knowledge, yes.
