### ISSUE TITLE
hr separator not allowed between code blocks and in poems

### ISSUE THREAD

**Issue by martinpub** [nlbdev/nordic-epub3-dtbook-migrator#521]
`<pre>` is a block-level element, but the following is not allowed according to the validator:

```
<pre><code>if (uttryck)
 sats;
else {
 en eller flera satser
}</code></pre>
<hr class="separator"/>
<pre><code>if (uttryck) {
 en eller flera satser
}
else
 sats;</code></pre>
```

The message from the validator is: "element 'pre' not allowed yet; missing required element 'p'". I think it is good not to overuse this separator, perhaps the separator in the example and should be solved with CSS to mark the boundaries of the pre/code sections? Perhaps my example is not the intended use of the hr sep. Let me know what you think.

**Comment by josteinaj** [comment]
My first thought is that hr would not be appropriate in this case, but I don't really have a strong opinion. In any case, it should be technically valid, so this is indeed a bug.

**Comment by martinpub** [comment]
And I would agree with you @josteinaj :-) I guess the interpretation depends on how much we want our productions to preserve separation marks from the print editions. I think the main case is in text to indicate a thematic break. In my example, we had several code examples and the "thematic break" semantics is much weaker there, since we have rather a list of examples. But I think I agree, it should be technically valid. It could be an accompanying task for guidelines development to clarify more about the use.

**Comment by oscarlcarlsson** [comment]
I have seen this happen in poems as well.

**Comment by josteinaj** [comment]
@martinpub @kalaspuffar solved?

**Comment by kalaspuffar** [comment]
To my knowledge, yes.
